log:
  dateFormat: "YYYY-MM-DD"
  datetimeFormat: "YYYY-MM-DD HH:mm:ss"
  jsonIndent: 2
cache:
  ttl: 300
  checkPeriod: 600
  useClones: false
express:
  requestSizeLimit: 50mb
permissions:
  roles:
    user:
      default: true
      permissions:
        - 'own.read'
        - 'own.write'
        - 'own.emotion.read'
        - 'own.emotion.write'
    admin:
      extends:
        - user
      permissions:
        - 'user.read'
        - 'user.write'
        - 'user.emotion.read'
        - 'user.emotion.write'
