log:
  dateFormat: "YYYY-MM-DD"
  datetimeFormat: "YYYY-MM-DD HH:mm:ss"
  jsonIndent: 2
cache:
  ttl: 300
  checkPeriod: 600
  useClones: false
express:
  requestSizeLimit: 50mb
permissions:
  roles:
    user:
      default: true
      permissions:
        - 'abcd'
        - '1234'
    admin:
      extends:
        - user
      permissions:
        - 'efgh'
        - '5678'
